name: Deploy Website

on:
  push:
    branches:
    - main
    release:
      types: [published, edited]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - run: pip install mkdocs-material mike
    - run: mike deploy ${{ github.ref_name }}

    - if: github.event_name == "release"
      run: mike alias -u ${{  github.ref_name }} latest
